services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=artifactory
      - POSTGRES_PASSWORD=artifactory
      - POSTGRES_DB=artifactory
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    environment:
      - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx2g
    volumes:
      - artifactory_data:/var/opt/jfrog/artifactory
      - ./system.yaml:/var/opt/jfrog/artifactory/etc/system.yaml
    ports:
      - "8080:8080"
    depends_on:
      - postgres

#  mongo:
#    image: mongo:latest
#    container_name: mongo-container
#    restart: unless-stopped
#    ports:
#      - "27017:27017"
#    volumes:
#      - mongo-data:/data/db

volumes:
  mysql-data:
  postgres_data:
  artifactory_data:
#  mongo-data:
