apiVersion: apps/v1
kind: Deployment
metadata:
  name: castlemock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: castlemock
  template:
    metadata:
      labels:
        app: castlemock
      annotations:
        env: "Ambiente develop"
    spec:
      containers:
      - name: castlemock
        image: castlemock/castlemock
        ports:
        - containerPort: 8080
        env:
        - name: NODE_ENV
          value: "production"
        volumeMounts:
        - mountPath: /data/castlemock
          name: castlemock-data
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"          
      volumes:
      - name: castlemock-data
        persistentVolumeClaim:
          claimName: castlemock-pvc
