apiVersion: v1
kind: Service
metadata:
  name: castlemock
  labels:
    app: castlemock
    version: v1
spec:
  selector:
    app: castlemock
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
